backend:
  name: git-gateway # or "github" / "gitlab" / "bitbucket"
  branch: main

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

site_url: "/"
logo_url: "/images/samples/sample-1.jpg"

collections:
  - name: "artworks"
    label: "Artworks"
    folder: "src/artworks"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["tattoo", "barro", "painting"] }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "lessons"
    label: "Lessons"
    folder: "src/lessons"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date & time", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Capacity", name: "capacity", widget: "number", value_type: "int" }
      - { label: "Description", name: "description", widget: "text", required: false }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/about.md"
        label: "About"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Intro", name: "intro", widget: "markdown", required: false }
          - { label: "Journey", name: "journey", widget: "markdown", required: false }
          - label: Offerings
            name: offerings
            widget: list
            summary: "{{fields.label}}"
            field: { label: Item, name: label, widget: string }
            required: false
          - { label: "Philosophy", name: "philosophy", widget: "markdown", required: false }
          - { label: "Location Note", name: "location_note", widget: "string", required: false }
      - file: "src/contact.njk"
        label: "Contact"
        name: "contact"
        fields:
          - { label: "Title", name: "title", widget: "string" }
      - file: "src/404.njk"
        label: "Not Found Page"
        name: "notfound"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body (HTML / Nunjucks allowed)", name: "body", widget: "markdown", required: false }

  - name: "settings"
    label: "Site Settings"
    files:
      - file: "src/_data/site.json"
        label: "General"
        name: "site"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - label: Social
            name: social
            widget: object
            fields:
              - { label: Instagram, name: instagram, widget: string }
              - { label: Email, name: email, widget: string }
          - { label: Location, name: location, widget: string }
          - { label: "Site URL", name: "url", widget: "string", required: false }
          - { label: "OG Image", name: "og_image", widget: "image", required: false }
          # Home hero editable fields
          - { label: "Hero Heading", name: "hero_heading", widget: "string", required: false }
          - { label: "Hero Subheading", name: "hero_subheading", widget: "string", required: false }
          - { label: "Hero Intro Text", name: "hero_intro", widget: "text", required: false }
          - { label: "Primary CTA Label", name: "hero_primary_cta_label", widget: "string", required: false }
          - { label: "Primary CTA URL", name: "hero_primary_cta_url", widget: "string", required: false }
          - { label: "Secondary CTA Label", name: "hero_secondary_cta_label", widget: "string", required: false }
          - { label: "Secondary CTA URL", name: "hero_secondary_cta_url", widget: "string", required: false }
          - label: "Hero Images"
            name: hero_images
            widget: list
            summary: "Image: {{fields.image}}"
            required: false
            field: { label: Image, name: image, widget: image }
          - { label: "Latest Artworks Heading", name: "latest_artworks_heading", widget: "string", required: false }
